[package]
name = "base1000"
version = "0.1.0"
authors = ["Li Hua <lihua@email.com>"]
edition = "2024"
readme = "README.md"
repository = "https://github.com/real-LiHua/Base1000QianZiWenCodec"
keywords = ["base1000"]
categories = ["command-line-utilities", "encoding"]
include = ["/src/*.rs"]

[features]


[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
num-bigint = "0.4.6"
rand = "0.9.0"
rust-embed = { version = "8.6.0", features = ["debug-embed", "include-exclude"] }
